[package]
name = "vimscript-format"
version = "0.1.0"
authors = ["Tomasz Zurkowski <tomasz.zurkowski@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vimscript-core = { path = "../vimscript-core" }
