[package]
name = "vimscript-core"
version = "0.1.0"
authors = ["Tomasz Zurkowski <zurkowski@google.com>"]
edition = "2018"

[dev-dependencies]
pretty_assertions = "0.6.1"

[dependencies]
serde_json = "1.0"
lsp-types = "0.80.0"
serde = { version = "1.0", features = ["derive"] }
